### ISSUE TITLE
OBS fails to build with CEF5060 due to #475 + #478 , and #477

### ISSUE THREAD

**Issue by DelTomix** [obsproject/obs-browser#480]
### Operating System Info

Other

### Other OS

Devuan Linux (Debian variant)

### OBS Studio Version

Git

### OBS Studio Log URL

N/A

### Expected Behavior

Successful build using CEF5060

### Current Behavior

Building with CEF 6533 completes without issue, building with CEF 5060 fails as follows;

```
[ 56%] Building CXX object plugins/obs-browser/CMakeFiles/obs-browser.dir/browser-client.cpp.o
In file included from /home/builder/obs/obs-port-31.0.0-153-g95dd4e9b3_5060_0/obs-studio/plugins/obs-browser/browser-client.cpp:19:
/home/builder/obs/obs-port-31.0.0-153-g95dd4e9b3_5060_0/obs-studio/plugins/obs-browser/browser-client.hpp:101:22: error: ‘virtual void BrowserClient::OnRenderProcessTerminated(CefRefPtr<CefBrowser>, CefRequestHandler::TerminationStatus, int, const CefString&)’ marked ‘override’, but does not override
  101 |         virtual void OnRenderProcessTerminated(CefRefPtr<CefBrowser> browser, TerminationStatus status, int error_code,
      |                      ^~~~~~~~~~~~~~~~~~~~~~~~~

```
Reverting #475 + #478 (commits 52c1527 and 46adc4b) solves this, but then #477 causes another failure;
```
/home/builder/obs/obs-port-31.0.0-153-ga269479c8_5060_0/obs-studio/plugins/obs-browser/obs-browser-plugin.cpp: In function ‘void BrowserInit()’:
/home/builder/obs/obs-port-31.0.0-153-ga269479c8_5060_0/obs-studio/plugins/obs-browser/obs-browser-plugin.cpp:386:91: error: ‘CefGetExitCode’ was not declared in this scope
  386 |                 blog(LOG_ERROR, "[obs-browser]: CEF failed to initialize. Exit code: %d", CefGetExitCode());
      |                                                                                           ^~~~~~~~~~~~~~

```

After additionally reverting #477 (commit af0651b) the build completes successfully with CEF5060, and runs as expected.

### Steps to Reproduce

1. Build obs-studio from current git master using CEF 5060
2.
3.
...

### Anything else we should know?

I had the impression that building with CEF 5060 is still intended to be supported as a stable fallback? Given issues reported with newer CEFs, and was building both to compare for my use case.
 
Build options used;
-DENABLE_RELOCATABLE=ON 
-DENABLE_PORTABLE_CONFIG=ON
-DCMAKE_BUILD_TYPE="Release" 
-DOBS_COMPILE_DEPRECATION_AS_WARNING=ON
-DCMAKE_INSTALL_PREFIX="${inst_parent}/obs-${obs_ver}" 
-DCEF_ROOT_DIR="${src_repo}/CEF_lib/${CEF_file}"
-DLibDataChannel_DIR="${build_parent}/3plib/ldc/lib/cmake/LibDataChannel"
-DENABLE_BROWSER=ON 
-DENABLE_BROWSER_PANELS=ON
-DENABLE_WEBRTC=ON
-DENABLE_RTMPS=ON 
-DENABLE_NEW_MPEGTS_OUTPUT=ON
-DENABLE_SERVICE_UPDATES=ON
-DENABLE_PULSEAUDIO=ON 
-DENABLE_PIPEWIRE=ON 
-DENABLE_LIBFDK=ON
-DENABLE_DECKLINK=OFF 
-DENABLE_VLC=OFF 
-DENABLE_JACK=OFF 
-DENABLE_SPEEXDSP=OFF
-DENABLE_RNNOISE=OFF 
-DENABLE_VST=OFF 
-DENABLE_OSS=OFF
-DENABLE_AJA=OFF

**Comment by WizardCM** [comment]
Hmm, this is not intentional. Looks like in the transition from [CEF 123](https://cef-builds.spotifycdn.com/docs/123.0/classCefRequestHandler.html#af196be960435c2f02f3b062c6232d01e) (6312) to [CEF 124](https://cef-builds.spotifycdn.com/docs/124.3/classCefRequestHandler.html#a6998e9b6ee7b0e9a810567fad3a6b4ea) (6367) the parameters changed.

Before:
```cpp
virtual void CefRequestHandler::OnRenderProcessTerminated(
	CefRefPtr<CefBrowser> browser,
	TerminationStatus status
)
```

After (what we currently support):
```cpp
virtual void CefRequestHandler::OnRenderProcessTerminated(
	CefRefPtr<CefBrowser> browser,
	TerminationStatus status,
	int error_code,
	const CefString &error_string
)	
```

I'll have to update our code to gracefully handle both versions.

**Comment by Fenrirthviti** [comment]
Unless there is a very compelling reason for us to carry this kind of workaround, I would recommend making the changes in a local fork, and maintaining it for that specific use case. I don't see us wanting to support old versions of CEF as a project at this point, and making this kind of change implies that we are.

I would like to keep it clear what we do and do not support in the master branch.

**Comment by WizardCM** [comment]
Generally, we intend to support n-1, in case of unexpected issues in the latest CEF (or to debug/troubleshoot/compare latest vs previous with the same obs-browser/obs-studio combination). Though yes, we recommend using the same version of CEF as our currently shipping release, we understand that's not always possible.
